### ISSUE TITLE
SPM issue

### ISSUE THREAD

**Issue by skywalkerlw** [exyte/ProgressIndicatorView#2]
I'm on Xcode 13.2 and it comes an error of

![image](https://user-images.githubusercontent.com/2090084/153779206-51c9565a-09ce-4f9c-ab59-76649887ed57.png)

**Comment by f3dm76** [comment]
Hey @skywalkerlw, sorry for slow response, issue is fixed in version 0.0.2, please check it out, have a wonderful day
