### ISSUE TITLE
Can we have an update with the latest XCode?

### ISSUE THREAD

**Issue by dpyy** [exyte/ProgressIndicatorView#4]
It doesn't seem to build, 1 compile error (asking about iOS 14) and after a manual fix, one warning about Non-constant range: argument must be an integer literal.

**Comment by f3dm76** [comment]
Hey @dpyy, there is no error on xcode 14.1, are you using 14.2? Could you please provide full error's text? Or point me to a line you want fixed? I fixed the "Non-constant range" one

**Comment by dpyy** [comment]
Yes I'm using 14.2. Sorry I don't have the error anymore sinceI made the changes locally. But it doesn't build in 14.2.

**Comment by f3dm76** [comment]
Hey @dpyy, please try version 0.0.3 - works on xcode 14.3. Don't hesitate to reopen if the problem persists, have a great day!
