### ISSUE TITLE
White animation seems to break on ZStack

### ISSUE THREAD

**Issue by dpyy** [exyte/ProgressIndicatorView#5]
A simple

ZStack {
   Rectangle()
   ProgressIndicatorView(isVisible: $showProgressIndicator,
                                  type: .impulseBar(progress: $progress, backgroundColor: .gray))
}

https://imgur.com/hFcGuD3

**Comment by f3dm76** [comment]
Hey @dpyy, sorry for the super late response, please check out version 1.0.0, should be fixed there. Have a great day!
