### ISSUE TITLE
xcode onchange(of:perform:) is only available in ios 14 or newer

### ISSUE THREAD

**Issue by artgryn** [exyte/ProgressIndicatorView#6]
Added dependency to the IOS 16 project and got error:

`xcode onchange(of:perform:) is only available in ios 14 or newer`

**Comment by f3dm76** [comment]
Hey @artgryn, thank you so much for bringing this to my attention. I'm happy to let you know the issue is fixed in version 0.0.4, please give it a try. Have a wonderful day!
